package otlp

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/http/httptest"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"google.golang.org/protobuf/encoding/protowire"

	"github.com/nicktill/tinyobs/pkg/labels"
	"github.com/nicktill/tinyobs/pkg/tsdb"
)

// expected is what Prometheus's OTLP receiver produces for testdata/metrics.*
// (generated by testdata/gen.py with the official OTLP protobuf classes).
var expected = map[string]string{
	`http_server_requests_total{http_response_status_code="200", http_route="/cart", instance="pod-1", job="shop/checkout"}`:    "42",
	`http_server_requests_total{http_response_status_code="500", http_route="/cart", instance="pod-1", job="shop/checkout"}`:    "3",
	`process_memory_usage_bytes{instance="pod-1", job="shop/checkout"}`:                                                         "1048576",
	`http_server_request_duration_seconds_bucket{http_route="/cart", instance="pod-1", job="shop/checkout", le="0.1"}`:          "5",
	`http_server_request_duration_seconds_bucket{http_route="/cart", instance="pod-1", job="shop/checkout", le="0.5"}`:          "8",
	`http_server_request_duration_seconds_bucket{http_route="/cart", instance="pod-1", job="shop/checkout", le="1"}`:            "9",
	`http_server_request_duration_seconds_bucket{http_route="/cart", instance="pod-1", job="shop/checkout", le="+Inf"}`:         "10",
	`http_server_request_duration_seconds_count{http_route="/cart", instance="pod-1", job="shop/checkout"}`:                     "10",
	`http_server_request_duration_seconds_sum{http_route="/cart", instance="pod-1", job="shop/checkout"}`:                       "3.25",
	`rpc_latency_milliseconds{instance="pod-1", job="shop/checkout", quantile="0.5"}`:                                           "0.125",
	`rpc_latency_milliseconds{instance="pod-1", job="shop/checkout", quantile="0.99"}`:                                          "0.875",
	`rpc_latency_milliseconds_count{instance="pod-1", job="shop/checkout"}`:                                                     "7",
	`rpc_latency_milliseconds_sum{instance="pod-1", job="shop/checkout"}`:                                                       "1.25",
	`queue_depth{instance="pod-1", job="shop/checkout"}`:                                                                        "stale",
	`cpu_utilization_ratio{instance="pod-1", job="shop/checkout", key_0weird="true", net_peer_name="db", tags="[\"a\",\"1\"]"}`: "0.5",
	`target_info{deployment_environment="dev", instance="pod-1", job="shop/checkout"}`:                                          "1",
}

func newHandler(t *testing.T) (*Handler, *tsdb.DB) {
	t.Helper()
	db, err := tsdb.Open(tsdb.Options{InMemory: true, Retention: 100 * 365 * 24 * time.Hour})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	return &Handler{DB: db, Now: func() time.Time { return time.Unix(1_700_000_100, 0) }}, db
}

func post(h http.Handler, contentType, encoding string, body []byte) *httptest.ResponseRecorder {
	req := httptest.NewRequest(http.MethodPost, "/v1/metrics", bytes.NewReader(body))
	req.Header.Set("Content-Type", contentType)
	if encoding != "" {
		req.Header.Set("Content-Encoding", encoding)
	}
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	return rec
}

func stored(t *testing.T, db *tsdb.DB) map[string]string {
	t.Helper()
	all, err := db.Select(context.Background(), 0, math.MaxInt64, 0, labels.MustNewMatcher(labels.MatchRegexp, "__name__", ".+"))
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]string{}
	for _, s := range all {
		if len(s.Samples) != 1 || s.Samples[0].T != 1_700_000_000_000 {
			t.Errorf("%s: samples %+v", s.Labels, s.Samples)
		}
		v := s.Samples[0].V
		str := strconv.FormatFloat(v, 'f', -1, 64)
		if math.IsInf(v, 1) {
			str = "+Inf"
		}
		if tsdb.IsStaleNaN(v) {
			str = "stale"
		}
		out[s.Labels.String()] = str
	}
	return out
}

func diff(got, want map[string]string) string {
	var lines []string
	for k, v := range want {
		if got[k] != v {
			lines = append(lines, fmt.Sprintf("  want %s = %s, got %q", k, v, got[k]))
		}
	}
	for k, v := range got {
		if _, ok := want[k]; !ok {
			lines = append(lines, fmt.Sprintf("  unexpected %s = %s", k, v))
		}
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}

func TestReceiveFixture(t *testing.T) {
	pb, err := os.ReadFile("testdata/metrics.pb")
	if err != nil {
		t.Fatal(err)
	}
	js, err := os.ReadFile("testdata/metrics.json")
	if err != nil {
		t.Fatal(err)
	}
	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	zw.Write(pb)
	zw.Close()

	for _, c := range []struct {
		name, contentType, encoding string
		body                        []byte
	}{
		{"protobuf", "application/x-protobuf", "", pb},
		{"json", "application/json", "", js},
		{"gzip protobuf", "application/x-protobuf", "gzip", gz.Bytes()},
	} {
		t.Run(c.name, func(t *testing.T) {
			h, db := newHandler(t)
			rec := post(h, c.contentType, c.encoding, c.body)
			if rec.Code != 200 {
				t.Fatalf("status %d: %s", rec.Code, rec.Body)
			}
			if d := diff(stored(t, db), expected); d != "" {
				t.Errorf("stored series differ:\n%s", d)
			}
			// Two points are rejected: the delta sum and the exponential histogram.
			rejected, msg := partialSuccess(t, rec, c.contentType == "application/json")
			if rejected != 2 || !strings.Contains(msg, "cumulative temporality") || !strings.Contains(msg, "exponential histograms") {
				t.Errorf("partial success = %d %q", rejected, msg)
			}
			md := db.Metadata()
			if md["http_server_requests_total"].Type != "counter" || md["http_server_requests_total"].Help != "Requests." {
				t.Errorf("counter metadata = %+v", md["http_server_requests_total"])
			}
			if md["http_server_request_duration_seconds"].Type != "histogram" || md["http_server_request_duration_seconds"].Unit != "seconds" {
				t.Errorf("histogram metadata = %+v", md["http_server_request_duration_seconds"])
			}
		})
	}
}

func partialSuccess(t *testing.T, rec *httptest.ResponseRecorder, isJSON bool) (int, string) {
	t.Helper()
	if isJSON {
		var body struct {
			PartialSuccess struct {
				RejectedDataPoints string `json:"rejectedDataPoints"`
				ErrorMessage       string `json:"errorMessage"`
			} `json:"partialSuccess"`
		}
		if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
			t.Fatal(err)
		}
		var n int
		fmt.Sscan(body.PartialSuccess.RejectedDataPoints, &n)
		return n, body.PartialSuccess.ErrorMessage
	}
	var n int
	var msg string
	if err := fields(rec.Body.Bytes(), func(num protowire.Number, typ protowire.Type, v []byte) (int, error) {
		b, l, err := bytesField(typ, v)
		if err != nil {
			return 0, err
		}
		return l, fields(b, func(num protowire.Number, typ protowire.Type, v []byte) (int, error) {
			switch num {
			case 1:
				x, l, err := varintField(typ, v)
				n = int(x)
				return l, err
			case 2:
				s, l, err := bytesField(typ, v)
				msg = string(s)
				return l, err
			}
			return -1, nil
		})
	}); err != nil {
		t.Fatal(err)
	}
	return n, msg
}

func TestReceiveErrors(t *testing.T) {
	h, _ := newHandler(t)
	cases := []struct {
		contentType, encoding string
		body                  []byte
		code                  int
	}{
		{"text/plain", "", []byte("x"), 415},
		{"application/x-protobuf", "br", []byte("x"), 415},
		{"application/x-protobuf", "gzip", []byte("not gzip"), 400},
		{"application/x-protobuf", "", []byte{0x0a, 0xff}, 400}, // truncated length-delimited field
		{"application/json", "", []byte(`{"resourceMetrics": 5}`), 400},
		{"application/x-protobuf", "", bytes.Repeat([]byte{0}, MaxBodyBytes+1), 413},
	}
	for i, c := range cases {
		rec := post(h, c.contentType, c.encoding, c.body)
		if rec.Code != c.code {
			t.Errorf("case %d: status %d, want %d (%s)", i, rec.Code, c.code, rec.Body)
		}
	}
	// An empty request is valid and stores nothing.
	if rec := post(h, "application/x-protobuf", "", nil); rec.Code != 200 || rec.Body.Len() != 0 {
		t.Errorf("empty request: %d %q", rec.Code, rec.Body)
	}
}

func TestJSONSpecialValues(t *testing.T) {
	h, db := newHandler(t)
	body := `{"resourceMetrics":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"svc"}}]},
	  "scopeMetrics":[{"metrics":[{"name":"temp","gauge":{"dataPoints":[
	    {"timeUnixNano":"1700000000000000000","asDouble":"NaN","attributes":[{"key":"k","value":{"stringValue":"nan"}}]},
	    {"timeUnixNano":"1700000000000000000","asDouble":"Infinity","attributes":[{"key":"k","value":{"stringValue":"inf"}}]},
	    {"timeUnixNano":1700000000000000000,"asInt":"-7","attributes":[{"key":"k","value":{"stringValue":"int"}}]}]}}]}]}]}`
	if rec := post(h, "application/json", "", []byte(body)); rec.Code != 200 {
		t.Fatalf("%d %s", rec.Code, rec.Body)
	}
	got := stored(t, db)
	if got[`temp{job="svc", k="nan"}`] != "NaN" || got[`temp{job="svc", k="inf"}`] != "+Inf" || got[`temp{job="svc", k="int"}`] != "-7" {
		t.Errorf("special values: %v", got)
	}
}

func TestMetricNames(t *testing.T) {
	cases := []struct {
		name, unit string
		counter    bool
		gauge      bool
		want       string
	}{
		{"http.server.duration", "ms", false, false, "http_server_duration_milliseconds"},
		{"http.server.requests", "{request}", true, false, "http_server_requests_total"},
		{"requests_total", "", true, false, "requests_total"},
		{"system.network.io", "By/s", false, true, "system_network_io_bytes_per_second"},
		{"cpu.utilization", "1", false, true, "cpu_utilization_ratio"},
		{"latency.seconds", "s", false, false, "latency_seconds"},
		{"2xx.count", "", true, false, "_2xx_count_total"},
		{"odd..name__x", "", false, true, "odd_name_x"},
	}
	for _, c := range cases {
		if got := metricName(c.name, c.unit, c.counter, c.gauge); got != c.want {
			t.Errorf("metricName(%q, %q) = %q, want %q", c.name, c.unit, got, c.want)
		}
	}
}

// The response to a fully accepted protobuf request is an empty message.
func TestFullSuccessResponse(t *testing.T) {
	h, _ := newHandler(t)
	js := `{"resourceMetrics":[{"scopeMetrics":[{"metrics":[{"name":"g","gauge":{"dataPoints":[{"timeUnixNano":"1700000000000000000","asDouble":1}]}}]}]}]}`
	rec := post(h, "application/json", "", []byte(js))
	body, _ := io.ReadAll(rec.Body)
	if rec.Code != 200 || strings.TrimSpace(string(body)) != "{}" {
		t.Fatalf("%d %s", rec.Code, body)
	}
}
